version: "3.8"

services:

  postgres:
    image: debezium/postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=test1
      - POSTGRES_PASSWORD=test1
      - POSTGRES_DB=test1
#    ports:
#      - "5432:5432"
      
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=sahandjalilvand@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=test1
#    ports:
#      - "8084:80"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
#    ports:
#      - "6379:6379"

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
#    ports:
#      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://kafka1:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka1-ui
    ports:
      - 8085:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      DYNAMIC_CONFIG_ENABLED: 'true'

  susbcription:
    image: sahand1990j/subscription
    container_name: susbcription
    ports:
      - 9090:8081
    environment:
      KAFKA_HOSTS: kafka1:9092
      DB_SERVER: postgres
      REDIS_HOST: redis

    depends_on:
      - postgres
      - kafka1


