server:
  port: ${APP_PORT:8081}
spring:
  application:
    name: ${APP_NAME:SUBSCRIPTION}

  profiles:
    include: ${APP_PROFILES:FileLogging, ConsoleLogging, Documentation}


  datasource:
    url: jdbc:postgresql://${subscription.rdbms.server}:${subscription.rdbms.port}/${subscription.rdbms.schema}
    username: ${subscription.rdbms.username}
    password: ${subscription.rdbms.pass}

    hikari:
      minimum-idle: ${DB_MIN_IDLE:1}
      maximum-pool-size: ${DB_POOL:6}
      leak-detection-threshold: {LEAK_DETECTION_THR:30000}

  jpa:
    hibernate:
      ddl-auto: ${ORM_MIGRATION:none}
    show-sql: ${DB_LOG:true}
    properties:
      hibernate.format_sql: ${FORMAT_DB_LOG:true}

    open-in-view: false

  liquibase:
    change-log: classpath:migration/master.xml
    enabled: ${LIQUIBASE_ENABLE:true}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


subscription:

  domain-event-channel: ${DOMAIN_EVENT_CHANNEL:DOMAIN_EVENTS}

  rdbms:
    server: ${DB_SERVER:localhost}
    port: ${DB_PORT:5432}
    schema: ${DB_SCHEMA:test1}
    username: ${DB_USER:test1}
    pass: ${DB_PASS:test1}

  kafka:
    kafka-hosts: ${KAFKA_HOSTS:localhost:9092}
    partitions: ${KAFKA_PARTITIONS:4}
    replicas: ${KAFKA_REPLICAS:1}
    timeout: ${KAFKA_TIMEOUT:6000}
    fail-fast: ${KAFKA_FAIL_FAST:true}
    retention: ${KAFKA_RETENTION:1}


  security:
    jwt:
      secret-key: ${SECRET_KEY:sbnkF8TnP9hstUjTDMDMP2DnlxBZF0LMapajPSOoLqDPw6LHnf9nQvXlamuaTOskPJ5Xu65zfhQ/ngu/be3p9Q==}
      expiration: ${EXPIRATION:3600000}


  cdc:
    connector-class: ${CDC_CONNECTOR_CLASS:io.debezium.connector.postgresql.PostgresConnector}
    offset-file: ${CDC_OFFSET_FILE:/offset/offset.dat}
    flush-interval: ${CDC_FLUSH_INTERVAL:6000}
    outbox-table: ${CDC_OUTBOX_TABLE:public.TBL_OUTBOX}

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: false